@host = http://127.0.0.1:9200

PUT {{host}}/ratings
Content-Type: application/json

{
  "mappings": {
    "properties": {
      "datetime": {
        "type": "date",
        "format": "epoch_second"
      }
    }
  }
}

